const fs = require('fs');

const original = {
  en: {
    translation: {
      nav: { home: "Home", tags: "Tags", search: "Search", contributors: "Contributors", admin: "Admin", ask: "Ask Question", sign_in: "Sign In" },
      home: { title: "Answers people actually lived through", subtitle: "Every answer here is a first-hand account. Nothing is marked Proven until other people who did the same thing confirm it matches.", topVerifiers: "Top verifiers this month", newest: "Newest", active: "Active", votes: "Votes", unanswered: "Unanswered", pinned: "Pinned", category_prefix: "Category: ", tag_prefix: "Tag: ", top_questions: "Top Questions", categories: "Categories", community_pulse: "Community Pulse", popular_tags: "Popular Tags", view_all_tags: "View all tags →", empty_state: { title: "No questions found", desc: "Try adjusting your filters or be the first to ask a question about this topic.", clear: "Clear Filters" }, stats: { questions: "Questions", answers: "Answers", members: "Members" } },
      question: { ask_title: "Ask a Question", title_label: "Title", body_label: "Details", tags_label: "Tags", submit: "Post Question", translation_original: "Original", translation_en: "English", translation_ar: "العربية", accept: "Accept", accepted: "Accepted Answer", views: "views", answers: "answers", vote_up: "Upvote", vote_down: "Downvote", related: "Related Questions", answer_this: "Your Answer", post_answer: "Post Answer", add_comment: "Add a comment...", submit_comment: "Post Comment", report: "Report" },
      profile: { reputation: "Reputation", badges: "Badges", activity: "Recent Activity", edit: "Edit Profile", save: "Save Changes", display_name: "Display Name", bio: "Bio", questions: "Questions", answers: "Answers" },
      search: { placeholder: "Search questions...", results: "Search Results", no_results: "No questions found.", filter_unanswered: "Unanswered only" },
      admin: { title: "Admin Overview", flags: "Flagged Content", users: "Users", tags: "Tags", transactions: "Transactions", dismiss: "Dismiss", remove: "Remove", suspend: "Suspend", restore: "Restore" },
      notifications: { title: "Notifications", mark_all_read: "Mark all as read", empty: "No new notifications" },
      common: { loading: "Loading...", error: "An error occurred", retry: "Retry", save: "Save", cancel: "Cancel", next: "Next", prev: "Previous", showing: "Showing {{start}} to {{end}} of {{total}}" },
      flag: { title: "Report Content", reason: "Reason for reporting", submit: "Submit Report" }
    }
  },
  ar: { translation: { nav: { home: "الرئيسية", tags: "الوسوم", search: "بحث", contributors: "المساهمون", admin: "الإدارة", ask: "اطرح سؤالاً", sign_in: "تسجيل الدخول" }, home: { title: "إجابات من أشخاص عاشوا التجربة", subtitle: "كل إجابة هنا هي رواية مباشرة. لا شيء يُعتبر مؤكداً حتى يؤكد أشخاص آخرون مروا بنفس التجربة تطابقه.", topVerifiers: "أبرز المحققين هذا الشهر", newest: "الأحدث", active: "النشطة", votes: "التصويتات", unanswered: "بدون إجابة", pinned: "مثبت", category_prefix: "الفئة: ", tag_prefix: "الوسم: ", top_questions: "أهم الأسئلة", categories: "الفئات", community_pulse: "نبض المجتمع", popular_tags: "الوسوم الشائعة", view_all_tags: "عرض كل الوسوم ←", empty_state: { title: "لا توجد أسئلة", desc: "حاول تعديل الفلاتر أو كن أول من يطرح سؤالاً حول هذا الموضوع.", clear: "مسح الفلاتر" }, stats: { questions: "أسئلة", answers: "إجابات", members: "أعضاء" } }, question: { ask_title: "اطرح سؤالاً", title_label: "العنوان", body_label: "التفاصيل", tags_label: "الوسوم", submit: "نشر السؤال", translation_original: "الأصلي", translation_en: "English", translation_ar: "العربية", accept: "قبول", accepted: "إجابة مقبولة", views: "مشاهدات", answers: "إجابات", vote_up: "تصويت إيجابي", vote_down: "تصويت سلبي", related: "أسئلة ذات صلة", answer_this: "إجابتك", post_answer: "نشر الإجابة", add_comment: "أضف تعليقاً...", submit_comment: "نشر التعليق", report: "إبلاغ" }, profile: { reputation: "السمعة", badges: "الأوسمة", activity: "النشاط الأخير", edit: "تعديل الملف", save: "حفظ التغييرات", display_name: "الاسم", bio: "نبذة", questions: "أسئلة", answers: "إجابات" }, search: { placeholder: "ابحث في الأسئلة...", results: "نتائج البحث", no_results: "لم يتم العثور على أسئلة.", filter_unanswered: "بدون إجابة فقط" }, admin: { title: "نظرة عامة", flags: "محتوى مبلّغ عنه", users: "المستخدمين", tags: "الوسوم", transactions: "المعاملات", dismiss: "تجاهل", remove: "إزالة", suspend: "إيقاف", restore: "استعادة" }, notifications: { title: "الإشعارات", mark_all_read: "تحديد الكل كمقروء", empty: "لا توجد إشعارات جديدة" }, common: { loading: "جاري التحميل...", error: "حدث خطأ", retry: "إعادة المحاولة", save: "حفظ", cancel: "إلغاء", next: "التالي", prev: "السابق", showing: "عرض {{start}} إلى {{end}} من {{total}}" }, flag: { title: "الإبلاغ عن محتوى", reason: "سبب الإبلاغ", submit: "إرسال البلاغ" } } },
  tl: { translation: { nav: { home: "Home", tags: "Mga Tag", search: "Hanapin", contributors: "Mga Nag-ambag", admin: "Admin", ask: "Magtanong", sign_in: "Mag-sign In" }, home: { title: "Mga sagot mula sa mga taong nakaranas nito", subtitle: "Bawat sagot dito ay mula sa sariling karanasan. Walang markang Patunayan hanggang hindi kinukumpirma ng iba na tumutugma ito.", topVerifiers: "Nangungunang mga tagasuri ngayong buwan", newest: "Pinakabago", active: "Aktibo", votes: "Boto", unanswered: "Walang sagot", pinned: "Naka-pin", category_prefix: "Kategorya: ", tag_prefix: "Tag: ", top_questions: "Nangungunang mga Tanong", categories: "Mga Kategorya", community_pulse: "Pulso ng Komunidad", popular_tags: "Sikat na mga Tag", view_all_tags: "Tingnan lahat ng tag →", empty_state: { title: "Walang nahanap na tanong", desc: "Subukang ayusin ang iyong mga filter o maging una na magtanong tungkol sa paksang ito.", clear: "I-clear ang mga Filter" }, stats: { questions: "Mga Tanong", answers: "Mga Sagot", members: "Mga Miyembro" } }, question: { ask_title: "Magtanong", title_label: "Pamagat", body_label: "Detalye", tags_label: "Mga Tag", submit: "I-post", translation_original: "Orihinal", translation_en: "Ingles", translation_ar: "Arabic", accept: "Tanggapin", accepted: "Tinanggap", views: "views", answers: "sagot", vote_up: "Upvote", vote_down: "Downvote", related: "Kaugnay", answer_this: "Ang iyong sagot", post_answer: "I-post ang sagot", add_comment: "Magkomento...", submit_comment: "I-post ang komento", report: "I-report" }, profile: { reputation: "Reputasyon", badges: "Mga Badge", activity: "Aktibidad", edit: "I-edit", save: "I-save", display_name: "Pangalan", bio: "Bio", questions: "Mga Tanong", answers: "Mga Sagot" }, search: { placeholder: "Maghanap...", results: "Mga Resulta", no_results: "Walang nahanap.", filter_unanswered: "Walang sagot lamang" }, admin: { title: "Admin", flags: "Mga Nai-report", users: "Mga User", tags: "Mga Tag", transactions: "Mga Transaksyon", dismiss: "I-dismiss", remove: "Alisin", suspend: "I-suspend", restore: "Ibalik" }, notifications: { title: "Mga Notipikasyon", mark_all_read: "Markahan lahat na nabasa", empty: "Walang bagong notipikasyon" }, common: { loading: "Naglo-load...", error: "May nangyaring error", retry: "Subukan muli", save: "I-save", cancel: "Kanselahin", next: "Susunod", prev: "Nakaraan", showing: "Ipinapakita ang {{start}} hanggang {{end}} sa {{total}}" }, flag: { title: "I-report", reason: "Dahilan", submit: "Isumite" } } },
  hi: { translation: { nav: { home: "मुख्य पृष्ठ", tags: "टैग्स", search: "खोजें", contributors: "योगदानकर्ता", admin: "व्यवस्थापक", ask: "प्रश्न पूछें", sign_in: "साइन इन" }, home: { title: "उन लोगों के उत्तर जिन्होंने वास्तव में इसे अनुभव किया है", subtitle: "यहां हर उत्तर प्रत्यक्ष अनुभव है। किसी भी चीज़ को तब तक प्रमाणित नहीं माना जाता जब तक कि उसी स्थिति से गुजरे अन्य लोग इसकी पुष्टि न करें।", topVerifiers: "इस महीने के शीर्ष सत्यापनकर्ता", newest: "नवीनतम", active: "सक्रिय", votes: "वोट", unanswered: "अनुत्तरित", pinned: "पिन किए गए", category_prefix: "श्रेणी: ", tag_prefix: "टैग: ", top_questions: "शीर्ष प्रश्न", categories: "श्रेणियां", community_pulse: "सामुदायिक पल्स", popular_tags: "लोकप्रिय टैग", view_all_tags: "सभी टैग देखें →", empty_state: { title: "कोई प्रश्न नहीं मिला", desc: "अपने फ़िल्टर समायोजित करने का प्रयास करें या इस विषय पर प्रश्न पूछने वाले पहले व्यक्ति बनें।", clear: "फ़िल्टर साफ़ करें" }, stats: { questions: "प्रश्न", answers: "उत्तर", members: "सदस्य" } }, question: { ask_title: "प्रश्न पूछें", title_label: "शीर्षक", body_label: "विवरण", tags_label: "टैग्स", submit: "पोस्ट करें", translation_original: "मूल", translation_en: "English", translation_ar: "العربية", accept: "स्वीकार करें", accepted: "स्वीकृत उत्तर", views: "बार देखा गया", answers: "उत्तर", vote_up: "अपवोट", vote_down: "डाउनवोट", related: "संबंधित प्रश्न", answer_this: "आपका उत्तर", post_answer: "उत्तर पोस्ट करें", add_comment: "टिप्पणी जोड़ें...", submit_comment: "टिप्पणी पोस्ट करें", report: "रिपोर्ट करें" }, profile: { reputation: "प्रतिष्ठा", badges: "बैज", activity: "हाल की गतिविधि", edit: "प्रोफ़ाइल संपादित करें", save: "सहेजें", display_name: "नाम", bio: "परिचय", questions: "प्रश्न", answers: "उत्तर" }, search: { placeholder: "प्रश्न खोजें...", results: "खोज परिणाम", no_results: "कोई प्रश्न नहीं मिला।", filter_unanswered: "केवल अनुत्तरित" }, admin: { title: "एडमिन", flags: "रिपोर्ट की गई सामग्री", users: "उपयोगकर्ता", tags: "टैग्स", transactions: "लेनदेन", dismiss: "खारिज करें", remove: "हटाएं", suspend: "निलंबित करें", restore: "पुनर्स्थापित करें" }, notifications: { title: "सूचनाएं", mark_all_read: "सभी को पढ़ा हुआ मानें", empty: "कोई नई सूचना नहीं" }, common: { loading: "लोड हो रहा है...", error: "एक त्रुटि हुई", retry: "पुनः प्रयास करें", save: "सहेजें", cancel: "रद्द करें", next: "अगला", prev: "पिछला", showing: "{{total}} में से {{start}} से {{end}} दिखा रहा है" }, flag: { title: "रिपोर्ट करें", reason: "रिपोर्ट का कारण", submit: "सबमिट करें" } } },
  zh: { translation: { nav: { home: "首页", tags: "标签", search: "搜索", contributors: "贡献者", admin: "管理", ask: "提问", sign_in: "登录" }, home: { title: "来自亲历者的回答", subtitle: "这里的每一个答案都是亲身经历。除非其他经历相同的人确认匹配，否则没有任何答案会被标记为已证明。", topVerifiers: "本月顶级验证者", newest: "最新", active: "活跃", votes: "投票", unanswered: "未回答", pinned: "置顶", category_prefix: "分类：", tag_prefix: "标签：", top_questions: "热门问题", categories: "分类", community_pulse: "社区动态", popular_tags: "热门标签", view_all_tags: "查看所有标签 →", empty_state: { title: "未找到问题", desc: "尝试调整筛选条件，或成为第一个提出该主题问题的人。", clear: "清除筛选条件" }, stats: { questions: "问题", answers: "回答", members: "成员" } }, question: { ask_title: "提问", title_label: "标题", body_label: "详情", tags_label: "标签", submit: "发布问题", translation_original: "原文", translation_en: "English", translation_ar: "العربية", accept: "接受", accepted: "已接受的答案", views: "次观看", answers: "个回答", vote_up: "赞同", vote_down: "反对", related: "相关问题", answer_this: "你的回答", post_answer: "发布回答", add_comment: "添加评论...", submit_comment: "发布评论", report: "举报" }, profile: { reputation: "声望", badges: "徽章", activity: "最近活动", edit: "编辑资料", save: "保存", display_name: "显示名称", bio: "简介", questions: "问题", answers: "回答" }, search: { placeholder: "搜索问题...", results: "搜索结果", no_results: "未找到问题", filter_unanswered: "仅限未回答" }, admin: { title: "管理概览", flags: "被举报内容", users: "用户", tags: "标签", transactions: "交易", dismiss: "忽略", remove: "移除", suspend: "封禁", restore: "恢复" }, notifications: { title: "通知", mark_all_read: "全部标为已读", empty: "没有新通知" }, common: { loading: "加载中...", error: "发生错误", retry: "重试", save: "保存", cancel: "取消", next: "下一页", prev: "上一页", showing: "显示第 {{start}} 到 {{end}} 条，共 {{total}} 条" }, flag: { title: "举报内容", reason: "举报原因", submit: "提交举报" } } },
  fr: { translation: { nav: { home: "Accueil", tags: "Tags", search: "Rechercher", contributors: "Contributeurs", admin: "Admin", ask: "Poser une question", sign_in: "Se connecter" }, home: { title: "Des réponses de personnes l'ayant vraiment vécu", subtitle: "Chaque réponse ici est un témoignage direct. Rien n'est marqué comme Prouvé tant que d'autres personnes ayant fait la même chose ne confirment pas.", topVerifiers: "Meilleurs vérificateurs ce mois-ci", newest: "Plus récent", active: "Actif", votes: "Votes", unanswered: "Sans réponse", pinned: "Épinglé", category_prefix: "Catégorie : ", tag_prefix: "Tag : ", top_questions: "Questions principales", categories: "Catégories", community_pulse: "Pouls de la communauté", popular_tags: "Tags populaires", view_all_tags: "Voir tous les tags →", empty_state: { title: "Aucune question trouvée", desc: "Essayez d'ajuster vos filtres ou soyez le premier à poser une question sur ce sujet.", clear: "Effacer les filtres" }, stats: { questions: "Questions", answers: "Réponses", members: "Membres" } }, question: { ask_title: "Poser une question", title_label: "Titre", body_label: "Détails", tags_label: "Tags", submit: "Publier", translation_original: "Original", translation_en: "Anglais", translation_ar: "Arabe", accept: "Accepter", accepted: "Réponse acceptée", views: "vues", answers: "réponses", vote_up: "Pour", vote_down: "Contre", related: "Questions similaires", answer_this: "Votre réponse", post_answer: "Publier la réponse", add_comment: "Ajouter un commentaire...", submit_comment: "Publier", report: "Signaler" }, profile: { reputation: "Réputation", badges: "Badges", activity: "Activité", edit: "Modifier", save: "Enregistrer", display_name: "Nom", bio: "Bio", questions: "Questions", answers: "Réponses" }, search: { placeholder: "Rechercher...", results: "Résultats", no_results: "Aucun résultat.", filter_unanswered: "Sans réponse" }, admin: { title: "Administration", flags: "Signalements", users: "Utilisateurs", tags: "Tags", transactions: "Transactions", dismiss: "Ignorer", remove: "Supprimer", suspend: "Suspendre", restore: "Restaurer" }, notifications: { title: "Notifications", mark_all_read: "Tout marquer comme lu", empty: "Aucune notification" }, common: { loading: "Chargement...", error: "Une erreur est survenue", retry: "Réessayer", save: "Enregistrer", cancel: "Annuler", next: "Suivant", prev: "Précédent", showing: "Affichage de {{start}} à {{end}} sur {{total}}" }, flag: { title: "Signaler", reason: "Raison", submit: "Envoyer" } } },
  es: { translation: { nav: { home: "Inicio", tags: "Etiquetas", search: "Buscar", contributors: "Colaboradores", admin: "Admin", ask: "Preguntar", sign_in: "Iniciar sesión" }, home: { title: "Respuestas de personas que lo vivieron", subtitle: "Cada respuesta aquí es un relato de primera mano. Nada se marca como Probado hasta que otras personas que hicieron lo mismo confirmen que coincide.", topVerifiers: "Mejores verificadores de este mes", newest: "Recientes", active: "Activas", votes: "Votos", unanswered: "Sin respuesta", pinned: "Fijado", category_prefix: "Categoría: ", tag_prefix: "Etiqueta: ", top_questions: "Preguntas principales", categories: "Categorías", community_pulse: "Pulso de la comunidad", popular_tags: "Etiquetas populares", view_all_tags: "Ver todas las etiquetas →", empty_state: { title: "No se encontraron preguntas", desc: "Intente ajustar sus filtros o sea el primero en hacer una pregunta sobre este tema.", clear: "Borrar filtros" }, stats: { questions: "Preguntas", answers: "Respuestas", members: "Miembros" } }, question: { ask_title: "Hacer una pregunta", title_label: "Título", body_label: "Detalles", tags_label: "Etiquetas", submit: "Publicar", translation_original: "Original", translation_en: "Inglés", translation_ar: "Árabe", accept: "Aceptar", accepted: "Respuesta aceptada", views: "vistas", answers: "respuestas", vote_up: "A favor", vote_down: "En contra", related: "Relacionadas", answer_this: "Tu respuesta", post_answer: "Publicar respuesta", add_comment: "Comentar...", submit_comment: "Publicar", report: "Reportar" }, profile: { reputation: "Reputación", badges: "Insignias", activity: "Actividad", edit: "Editar perfil", save: "Guardar", display_name: "Nombre", bio: "Biografía", questions: "Preguntas", answers: "Respuestas" }, search: { placeholder: "Buscar...", results: "Resultados", no_results: "Sin resultados.", filter_unanswered: "Solo sin respuesta" }, admin: { title: "Administración", flags: "Reportes", users: "Usuarios", tags: "Etiquetas", transactions: "Transacciones", dismiss: "Descartar", remove: "Eliminar", suspend: "Suspender", restore: "Restaurar" }, notifications: { title: "Notificaciones", mark_all_read: "Marcar leídas", empty: "Sin notificaciones" }, common: { loading: "Cargando...", error: "Error", retry: "Reintentar", save: "Guardar", cancel: "Cancelar", next: "Siguiente", prev: "Anterior", showing: "Mostrando de {{start}} a {{end}} de {{total}}" }, flag: { title: "Reportar", reason: "Razón", submit: "Enviar" } } },
  ru: { translation: { nav: { home: "Главная", tags: "Теги", search: "Поиск", contributors: "Участники", admin: "Админ", ask: "Задать вопрос", sign_in: "Войти" }, home: { title: "Ответы людей, которые действительно пережили это", subtitle: "Каждый ответ здесь — из первых уст. Ничто не помечается как Доказанное, пока другие люди, оказавшиеся в такой же ситуации, не подтвердят это.", topVerifiers: "Лучшие верификаторы в этом месяце", newest: "Новые", active: "Активные", votes: "Голоса", unanswered: "Без ответа", pinned: "Закрепленные", category_prefix: "Категория: ", tag_prefix: "Тег: ", top_questions: "Популярные вопросы", categories: "Категории", community_pulse: "Пульс сообщества", popular_tags: "Популярные теги", view_all_tags: "Все теги →", empty_state: { title: "Вопросы не найдены", desc: "Попробуйте изменить фильтры или станьте первым, кто задаст вопрос на эту тему.", clear: "Очистить фильтры" }, stats: { questions: "Вопросы", answers: "Ответы", members: "Участники" } }, question: { ask_title: "Задать вопрос", title_label: "Заголовок", body_label: "Детали", tags_label: "Теги", submit: "Опубликовать", translation_original: "Оригинал", translation_en: "Английский", translation_ar: "Арабский", accept: "Принять", accepted: "Принятый ответ", views: "просмотров", answers: "ответов", vote_up: "За", vote_down: "Против", related: "Связанные", answer_this: "Ваш ответ", post_answer: "Ответить", add_comment: "Комментировать...", submit_comment: "Отправить", report: "Жалоба" }, profile: { reputation: "Репутация", badges: "Значки", activity: "Активность", edit: "Редактировать", save: "Сохранить", display_name: "Имя", bio: "О себе", questions: "Вопросы", answers: "Ответы" }, search: { placeholder: "Поиск...", results: "Результаты", no_results: "Нет результатов.", filter_unanswered: "Только без ответа" }, admin: { title: "Админ-панель", flags: "Жалобы", users: "Пользователи", tags: "Теги", transactions: "Транзакции", dismiss: "Отклонить", remove: "Удалить", suspend: "Заблокировать", restore: "Восстановить" }, notifications: { title: "Уведомления", mark_all_read: "Прочитать все", empty: "Нет новых" }, common: { loading: "Загрузка...", error: "Ошибка", retry: "Повторить", save: "Сохранить", cancel: "Отмена", next: "Вперед", prev: "Назад", showing: "Показано с {{start}} по {{end}} из {{total}}" }, flag: { title: "Пожаловаться", reason: "Причина", submit: "Отправить" } } },
  uk: { translation: { nav: { home: "Головна", tags: "Теги", search: "Пошук", contributors: "Учасники", admin: "Адмін", ask: "Запитати", sign_in: "Увійти" }, home: { title: "Відповіді людей, які дійсно пережили це", subtitle: "Кожна відповідь тут — з перших вуст. Ніщо не позначається як Доведене, доки інші люди, які пройшли через те саме, не підтвердять це.", topVerifiers: "Найкращі верифікатори цього місяця", newest: "Нові", active: "Активні", votes: "Голоси", unanswered: "Без відповіді", pinned: "Закріплені", category_prefix: "Категорія: ", tag_prefix: "Тег: ", top_questions: "Популярні питання", categories: "Категорії", community_pulse: "Пульс спільноти", popular_tags: "Популярні теги", view_all_tags: "Всі теги →", empty_state: { title: "Питання не знайдені", desc: "Спробуйте змінити фільтри або станьте першим, хто задасть питання на цю тему.", clear: "Очистити фільтри" }, stats: { questions: "Питання", answers: "Відповіді", members: "Учасники" } }, question: { ask_title: "Задати питання", title_label: "Заголовок", body_label: "Деталі", tags_label: "Теги", submit: "Опублікувати", translation_original: "Оригінал", translation_en: "Англійська", translation_ar: "Арабська", accept: "Прийняти", accepted: "Прийнята відповідь", views: "переглядів", answers: "відповідей", vote_up: "За", vote_down: "Проти", related: "Пов'язані", answer_this: "Ваша відповідь", post_answer: "Відповісти", add_comment: "Коментувати...", submit_comment: "Надіслати", report: "Скарга" }, profile: { reputation: "Репутация", badges: "Значки", activity: "Активність", edit: "Редактировать", save: "Зберегти", display_name: "Ім'я", bio: "Про себе", questions: "Питання", answers: "Відповіді" }, search: { placeholder: "Пошук...", results: "Результати", no_results: "Немає результатів.", filter_unanswered: "Тільки без відповіді" }, admin: { title: "Адмін-панель", flags: "Скарги", users: "Користувачі", tags: "Теги", transactions: "Транзакції", dismiss: "Відхилити", remove: "Видалити", suspend: "Заблокувати", restore: "Відновити" }, notifications: { title: "Сповіщення", mark_all_read: "Прочитати всі", empty: "Немає нових" }, common: { loading: "Завантаження...", error: "Помилка", retry: "Повторити", save: "Зберегти", cancel: "Скасувати", next: "Вперед", prev: "Назад", showing: "Показано з {{start}} по {{end}} з {{total}}" }, flag: { title: "Поскаржитися", reason: "Причина", submit: "Надіслати" } } },
  fa: { translation: { nav: { home: "خانه", tags: "برچسب‌ها", search: "جستجو", contributors: "مشارکت‌کنندگان", admin: "مدیریت", ask: "پرسیدن سوال", sign_in: "ورود" }, home: { title: "پاسخ از افرادی که واقعاً آن را تجربه کرده‌اند", subtitle: "هر پاسخ در اینجا یک روایت دست اول است. هیچ چیز تایید شده علامت‌گذاری نمی‌شود تا زمانی که دیگرانی که همان کار را انجام داده‌اند آن را تایید کنند.", topVerifiers: "برترین تاییدکنندگان این ماه", newest: "جدیدترین", active: "فعال", votes: "آرا", unanswered: "بدون پاسخ", pinned: "سنجاق شده", category_prefix: "دسته‌بندی: ", tag_prefix: "برچسب: ", top_questions: "سوالات برتر", categories: "دسته‌بندی‌ها", community_pulse: "نبض جامعه", popular_tags: "برچسب‌های محبوب", view_all_tags: "مشاهده همه برچسب‌ها ←", empty_state: { title: "سوالی یافت نشد", desc: "فیلترهای خود را تغییر دهید یا اولین نفری باشید که در این مورد سوال می‌پرسید.", clear: "پاک کردن فیلترها" }, stats: { questions: "سوالات", answers: "پاسخ‌ها", members: "اعضا" } }, question: { ask_title: "پرسیدن سوال", title_label: "عنوان", body_label: "جزئیات", tags_label: "برچسب‌ها", submit: "ارسال", translation_original: "اصلی", translation_en: "انگلیسی", translation_ar: "عربی", accept: "پذیرش", accepted: "پاسخ پذیرفته شده", views: "بازدید", answers: "پاسخ", vote_up: "موافق", vote_down: "مخالف", related: "مرتبط", answer_this: "پاسخ شما", post_answer: "ارسال پاسخ", add_comment: "ثبت نظر...", submit_comment: "ارسال", report: "گزارش" }, profile: { reputation: "اعتبار", badges: "نشان‌ها", activity: "فعالیت‌ها", edit: "ویرایش", save: "ذخیره", display_name: "نام", bio: "درباره من", questions: "سوالات", answers: "پاسخ‌ها" }, search: { placeholder: "جستجو...", results: "نتایج", no_results: "موردی یافت نشد.", filter_unanswered: "فقط بدون پاسخ" }, admin: { title: "مدیریت", flags: "گزارش‌ها", users: "کاربران", tags: "برچسب‌ها", transactions: "تراکنش‌ها", dismiss: "رد", remove: "حذف", suspend: "تعلیق", restore: "بازیابی" }, notifications: { title: "اعلان‌ها", mark_all_read: "خواندن همه", empty: "بدون اعلان جدید" }, common: { loading: "در حال بارگذاری...", error: "خطا رخ داد", retry: "تلاش مجدد", save: "ذخیره", cancel: "لغو", next: "بعدی", prev: "قبلی", showing: "نمایش {{start}} تا {{end}} از {{total}}" }, flag: { title: "گزارش تخلف", reason: "دلیل", submit: "ارسال" } } },
  ur: { translation: { nav: { home: "ہوم", tags: "ٹیگز", search: "تلاش", contributors: "معاونین", admin: "ایڈمن", ask: "سوال پوچھیں", sign_in: "سائن ان" }, home: { title: "ان لوگوں کے جوابات جنہوں نے واقعی اس کا تجربہ کیا", subtitle: "یہاں ہر جواب ایک براہ راست تجربہ ہے۔ کوئی بھی چیز اس وقت تک ثابت شدہ قرار نہیں دی جاتی جب تک کہ دوسرے لوگ جنہوں نے وہی کیا ہے اس کی تصدیق نہ کریں۔", topVerifiers: "اس مہینے کے ٹاپ تصدیق کنندگان", newest: "تازہ ترین", active: "فعال", votes: "ووٹ", unanswered: "بغیر جواب", pinned: "پن کردہ", category_prefix: "زمرہ: ", tag_prefix: "ٹیگ: ", top_questions: "اہم سوالات", categories: "زمرے", community_pulse: "کمیونٹی کی دھڑکن", popular_tags: "مقبول ٹیگز", view_all_tags: "تمام ٹیگز دیکھیں ←", empty_state: { title: "کوئی سوال نہیں ملا", desc: "اپنے فلٹرز کو تبدیل کرنے کی کوشش کریں یا اس موضوع پر سوال پوچھنے والے پہلے شخص بنیں۔", clear: "فلٹرز صاف کریں" }, stats: { questions: "سوالات", answers: "جوابات", members: "ارکان" } }, question: { ask_title: "سوال پوچھیں", title_label: "عنوان", body_label: "تفصیلات", tags_label: "ٹیگز", submit: "شائع کریں", translation_original: "اصل", translation_en: "انگریزی", translation_ar: "عربی", accept: "قبول کریں", accepted: "منظور شدہ جواب", views: "مناظر", answers: "جوابات", vote_up: "اپ ووٹ", vote_down: "ڈاؤن ووٹ", related: "متعلقہ", answer_this: "آپ کا جواب", post_answer: "جواب شائع کریں", add_comment: "تبصرہ کریں...", submit_comment: "شائع کریں", report: "رپورٹ" }, profile: { reputation: "ساکھ", badges: "بیج", activity: "سرگرمی", edit: "ترمیم", save: "محفوظ کریں", display_name: "نام", bio: "تعارف", questions: "سوالات", answers: "جوابات" }, search: { placeholder: "تلاش کریں...", results: "نتائج", no_results: "کوئی نتیجہ نہیں", filter_unanswered: "صرف بغیر جواب" }, admin: { title: "ایڈمن", flags: "رپورٹس", users: "صارفین", tags: "ٹیگز", transactions: "لین دین", dismiss: "مسترد", remove: "حذف کریں", suspend: "معطل کریں", restore: "بحال کریں" }, notifications: { title: "اطلاعات", mark_all_read: "سب پڑھ لیں", empty: "کوئی نئی اطلاع نہیں" }, common: { loading: "لوڈ ہو رہا ہے...", error: "غلطی", retry: "دوبارہ کوشش کریں", save: "محفوظ کریں", cancel: "منسوخ", next: "اگلا", prev: "پچھلا", showing: "{{total}} میں سے {{start}} سے {{end}} دکھا رہا ہے" }, flag: { title: "رپورٹ کریں", reason: "وجہ", submit: "جمع کریں" } } },
  bn: { translation: { nav: { home: "হোম", tags: "ট্যাগ", search: "অনুসন্ধান", contributors: "অবদানকারী", admin: "অ্যাডমিন", ask: "প্রশ্ন করুন", sign_in: "সাইন ইন" }, home: { title: "যাঁরা সত্যিই অভিজ্ঞতা অর্জন করেছেন তাঁদের উত্তর", subtitle: "এখানকার প্রতিটি উত্তর প্রথম হাতের অভিজ্ঞতা। অন্যান্য মানুষ যারা একই কাজ করেছে তারা এটি নিশ্চিত না করা পর্যন্ত কোন কিছু প্রমাণিত হিসেবে চিহ্নিত করা হয় অচ।", topVerifiers: "এই মাসে শীর্ষ যাচাইকারী", newest: "নতুন", active: "সক্রিয়", votes: "ভোট", unanswered: "উত্তরহীন", pinned: "পিন করা", category_prefix: "বিভাগ: ", tag_prefix: "ট্যাগ: ", top_questions: "শীর্ষ প্রশ্ন", categories: "বিভাগ", community_pulse: "কমিউনিটি পালস", popular_tags: "জনপ্রিয় ট্যাগ", view_all_tags: "সব ট্যাগ দেখুন →", empty_state: { title: "কোন প্রশ্ন পাওয়া যায়নি", desc: "আপনার ফিল্টারগুলি সামঞ্জস্য করার চেষ্টা করুন বা এই বিষয়ে প্রশ্ন জিজ্ঞাসা করার প্রথম ব্যক্তি হন।", clear: "ফিল্টার সাফ করুন" }, stats: { questions: "প্রশ্ন", answers: "উত্তর", members: "সদস্য" } }, question: { ask_title: "প্রশ্ন করুন", title_label: "শিরোনাম", body_label: "বিস্তারিত", tags_label: "ট্যাগ", submit: "পোস্ট করুন", translation_original: "আসল", translation_en: "ইংরেজি", translation_ar: "আরবি", accept: "গ্রহণ করুন", accepted: "গৃহীত উত্তর", views: "ভিউ", answers: "উত্তর", vote_up: "আপভোট", vote_down: "ডাউনভোট", related: "সম্পর্কিত", answer_this: "আপনার উত্তর", post_answer: "উত্তর পোস্ট করুন", add_comment: "মন্তব্য যোগ করুন...", submit_comment: "পোস্ট করুন", report: "রিপোর্ট" }, profile: { reputation: "সুনাম", badges: "ব্যাজ", activity: "কার্যকলাপ", edit: "সম্পাদনা", save: "সংরক্ষণ", display_name: "নাম", bio: "বায়ো", questions: "প্রশ্ন", answers: "উত্তর" }, search: { placeholder: "অনুসন্ধান...", results: "ফলাফল", no_results: "কিছু পাওয়া যায়নি", filter_unanswered: "শুধুমাত্র উত্তরহীন" }, admin: { title: "অ্যাডমিন", flags: "রিপোর্ট", users: "ব্যবহারকারী", tags: "ট্যাগ", transactions: "লেনদেন", dismiss: "বাতিল", remove: "মুছুন", suspend: "সাসপেন্ড", restore: "পুনরুদ্ধার" }, notifications: { title: "বিজ্ঞপ্তি", mark_all_read: "সব পড়া হিসেবে চিহ্নিত করুন", empty: "কোন নতুন বিজ্ঞপ্তি নেই" }, common: { loading: "লোড হচ্ছে...", error: "ত্রুটি", retry: "পুনরায় চেষ্টা করুন", save: "সংরক্ষণ", cancel: "বাতিল", next: "পরবর্তী", prev: "পূর্ববর্তী", showing: "{{total}} এর মধ্যে {{start}} থেকে {{end}} দেখানো হচ্ছে" }, flag: { title: "রিপোর্ট করুন", reason: "কারণ", submit: "জমা দিন" } } },
  tr: { translation: { nav: { home: "Ana Sayfa", tags: "Etiketler", search: "Ara", contributors: "Katkıda Bulunanlar", admin: "Yönetici", ask: "Soru Sor", sign_in: "Giriş Yap" }, home: { title: "Bunu gerçekten yaşamış kişilerin cevapları", subtitle: "Buradaki her cevap birinci elden bir hesaptır. Aynı şeyi yapan diğer insanlar onaylayana kadar hiçbir şey Kanıtlanmış olarak işaretlenmez.", topVerifiers: "Bu ayın en iyi doğrulayıcıları", newest: "En Yeni", active: "Aktif", votes: "Oylar", unanswered: "Cevapsız", pinned: "Sabitlenmiş", category_prefix: "Kategori: ", tag_prefix: "Etiket: ", top_questions: "Popüler Sorular", categories: "Kategoriler", community_pulse: "Topluluk Nabzı", popular_tags: "Popüler Etiketler", view_all_tags: "Tüm etiketleri gör →", empty_state: { title: "Soru bulunamadı", desc: "Filtrelerinizi ayarlamayı deneyin veya bu konu hakkında soru soran ilk kişi siz olun.", clear: "Filtreleri Temizle" }, stats: { questions: "Sorular", answers: "Cevaplar", members: "Üyeler" } }, question: { ask_title: "Soru Sor", title_label: "Başlık", body_label: "Detaylar", tags_label: "Etiketler", submit: "Gönder", translation_original: "Orijinal", translation_en: "İngilizce", translation_ar: "Arapça", accept: "Kabul Et", accepted: "Kabul Edilen Cevap", views: "görüntülenme", answers: "cevap", vote_up: "Katılıyorum", vote_down: "Katılmıyorum", related: "İlgili", answer_this: "Cevabınız", post_answer: "Cevabı Gönder", add_comment: "Yorum ekle...", submit_comment: "Gönder", report: "Bildir" }, profile: { reputation: "İtibar", badges: "Rozetler", activity: "Aktivite", edit: "Düzenle", save: "Kaydet", display_name: "Ad", bio: "Hakkımda", questions: "Sorular", answers: "Cevaplar" }, search: { placeholder: "Ara...", results: "Sonuçlar", no_results: "Sonuç bulunamadı.", filter_unanswered: "Sadece cevapsızlar" }, admin: { title: "Yönetim", flags: "Şikayetler", users: "Kullanıcılar", tags: "Etiketler", transactions: "İşlemler", dismiss: "Yoksay", remove: "Kaldır", suspend: "Askıya Al", restore: "Geri Getir" }, notifications: { title: "Bildirimler", mark_all_read: "Tümünü okundu işaretle", empty: "Yeni bildirim yok" }, common: { loading: "Yükleniyor...", error: "Hata", retry: "Tekrar Dene", save: "Kaydet", cancel: "İptal", next: "İleri", prev: "Geri", showing: "{{total}} kayıttan {{start}} ile {{end}} arası gösteriliyor" }, flag: { title: "Bildir", reason: "Sebep", submit: "Gönder" } } }
};

const additions = {
  en: {
    nav: { about: "About", products: "Products", blog: "Blog" },
    about: { title: "About The Proven X", story_title: "Our Story", story_body: "The Proven X was built for a simple reason: generic advice doesn't work. We want answers from people who have actually lived through the experience.", promise_title: "The Proven Promise", promise_body: "Nothing is marked Proven until other people who did the exact same thing confirm it matches. No theories, just verified experience.", ads_title: "Proven Ads", ads_body: "Reach a highly engaged, trusting audience. Our community values authenticity above all else.", ads_cta: "Advertise with us" },
    products: { title: "Our Products", subtitle: "Experience The Proven X anywhere.", web: "Web Community", web_desc: "The core platform for asking, answering, and verifying.", mobile: "Mobile App", mobile_desc: "Take the community on the go. Available now.", plans: "Plans", free: "Free", free_desc: "Full access to read and contribute.", paid: "Pro", paid_desc: "Advanced features and priority support.", coming_soon: "Coming Soon" },
    blog: { title: "Blog", read_more: "Read More" }
  },
  ar: {
    nav: { about: "حول", products: "المنتجات", blog: "المدونة" },
    about: { title: "حول The Proven X", story_title: "قصتنا", story_body: "تم بناء The Proven X لسبب بسيط: النصائح العامة لا تنجح. نريد إجابات من أشخاص عاشوا التجربة بالفعل.", promise_title: "الوعد المؤكد", promise_body: "لا شيء يُعتبر مؤكداً حتى يؤكد أشخاص آخرون مروا بنفس التجربة تطابقه. لا نظريات، فقط تجارب موثقة.", ads_title: "إعلانات مؤكدة", ads_body: "الوصول إلى جمهور متفاعل وواثق. مجتمعنا يقدر الأصالة قبل كل شيء.", ads_cta: "أعلن معنا" },
    products: { title: "منتجاتنا", subtitle: "استمتع بـ The Proven X في أي مكان.", web: "مجتمع الويب", web_desc: "المنصة الأساسية للسؤال والإجابة والتحقق.", mobile: "تطبيق الهاتف", mobile_desc: "خذ المجتمع معك أينما ذهبت. متاح الآن.", plans: "الخطط", free: "مجاني", free_desc: "وصول كامل للقراءة والمساهمة.", paid: "برو", paid_desc: "ميزات متقدمة ودعم ذو أولوية.", coming_soon: "قريباً" },
    blog: { title: "المدونة", read_more: "اقرأ المزيد" }
  },
  tl: {
    nav: { about: "Tungkol", products: "Mga Produkto", blog: "Blog" },
    about: { title: "Tungkol sa The Proven X", story_title: "Aming Kwento", story_body: "Ang The Proven X ay binuo para sa isang simpleng dahilan: hindi epektibo ang pangkalahatang payo. Gusto namin ng mga sagot mula sa mga taong nakaranas na nito.", promise_title: "Ang Pangako", promise_body: "Walang markang Patunayan hanggang hindi kinukumpirma ng iba na tumutugma ito. Walang teorya, tanging kumpirmadong karanasan lamang.", ads_title: "Mga Patalastas", ads_body: "Abutin ang isang aktibo at nagtitiwalang madla. Pinahahalagahan ng aming komunidad ang pagiging tunay higit sa lahat.", ads_cta: "Mag-advertise sa amin" },
    products: { title: "Aming Mga Produkto", subtitle: "Damhin ang The Proven X kahit saan.", web: "Komunidad sa Web", web_desc: "Ang pangunahing platform para sa pagtatanong, pagsagot, at pagpapatunay.", mobile: "Mobile App", mobile_desc: "Dalhin ang komunidad kahit saan. Available na ngayon.", plans: "Mga Plano", free: "Libre", free_desc: "Buong access para magbasa at mag-ambag.", paid: "Pro", paid_desc: "Mga advanced na feature at priority support.", coming_soon: "Malapit Na" },
    blog: { title: "Blog", read_more: "Magbasa pa" }
  },
  hi: {
    nav: { about: "बारे में", products: "उत्पाद", blog: "ब्लॉग" },
    about: { title: "The Proven X के बारे में", story_title: "हमारी कहानी", story_body: "The Proven X को एक साधारण कारण से बनाया गया था: सामान्य सलाह काम नहीं करती। हम उन लोगों से उत्तर चाहते हैं जिन्होंने वास्तव में अनुभव किया है।", promise_title: "हमारा वादा", promise_body: "किसी भी चीज़ को तब तक प्रमाणित नहीं माना जाता जब तक कि उसी स्थिति से गुजरे अन्य लोग इसकी पुष्टि न करें। कोई सिद्धांत नहीं, केवल सत्यापित अनुभव।", ads_title: "विज्ञापन", ads_body: "एक सक्रिय और विश्वास करने वाले दर्शकों तक पहुँचें। हमारा समुदाय सबसे ऊपर प्रामाणिकता को महत्व देता है।", ads_cta: "हमारे साथ विज्ञापन करें" },
    products: { title: "हमारे उत्पाद", subtitle: "The Proven X का अनुभव कहीं भी करें।", web: "वेब समुदाय", web_desc: "पूछने, उत्तर देने और सत्यापित करने के लिए मुख्य मंच।", mobile: "मोबाइल ऐप", mobile_desc: "समुदाय को अपने साथ ले जाएं। अब उपलब्ध है।", plans: "योजनाएं", free: "मुफ़्त", free_desc: "पढ़ने और योगदान करने के लिए पूर्ण पहुँच।", paid: "प्रो", paid_desc: "उन्नत सुविधाएँ और प्राथमिकता समर्थन।", coming_soon: "जल्द आ रहा है" },
    blog: { title: "ब्लॉग", read_more: "और पढ़ें" }
  },
  zh: {
    nav: { about: "关于", products: "产品", blog: "博客" },
    about: { title: "关于 The Proven X", story_title: "我们的故事", story_body: "创建 The Proven X 的原因很简单：泛泛的建议不起作用。我们希望得到那些亲历者的回答。", promise_title: "我们的承诺", promise_body: "除非其他经历相同的人确认匹配，否则没有任何答案会被标记为已证明。没有理论，只有经过验证的经验。", ads_title: "广告", ads_body: "接触高度参与、充满信任的受众。我们的社区最看重真实性。", ads_cta: "与我们合作广告" },
    products: { title: "我们的产品", subtitle: "随时随地体验 The Proven X。", web: "Web 社区", web_desc: "提问、回答和验证的核心平台。", mobile: "移动应用", mobile_desc: "将社区随身携带。现已推出。", plans: "计划", free: "免费", free_desc: "完全访问权限以阅读和贡献。", paid: "专业版", paid_desc: "高级功能和优先支持。", coming_soon: "敬请期待" },
    blog: { title: "博客", read_more: "阅读更多" }
  },
  fr: {
    nav: { about: "À propos", products: "Produits", blog: "Blog" },
    about: { title: "À propos de The Proven X", story_title: "Notre histoire", story_body: "The Proven X a été conçu pour une raison simple : les conseils génériques ne fonctionnent pas. Nous voulons des réponses de personnes qui ont réellement vécu l'expérience.", promise_title: "Notre promesse", promise_body: "Rien n'est marqué comme Prouvé tant que d'autres personnes ayant fait la même chose ne confirment pas. Pas de théories, que de l'expérience vérifiée.", ads_title: "Publicités", ads_body: "Atteignez un public très engagé et confiant. Notre communauté valorise l'authenticité par-dessus tout.", ads_cta: "Annoncez avec nous" },
    products: { title: "Nos produits", subtitle: "Découvrez The Proven X partout.", web: "Communauté Web", web_desc: "La plateforme principale pour poser des questions, répondre et vérifier.", mobile: "Application mobile", mobile_desc: "Emportez la communauté avec vous. Disponible maintenant.", plans: "Forfaits", free: "Gratuit", free_desc: "Accès complet pour lire et contribuer.", paid: "Pro", paid_desc: "Fonctionnalités avancées et support prioritaire.", coming_soon: "Bientôt disponible" },
    blog: { title: "Blog", read_more: "Lire la suite" }
  },
  es: {
    nav: { about: "Acerca de", products: "Productos", blog: "Blog" },
    about: { title: "Acerca de The Proven X", story_title: "Nuestra historia", story_body: "The Proven X fue creado por una sencilla razón: los consejos genéricos no funcionan. Queremos respuestas de personas que realmente hayan vivido la experiencia.", promise_title: "Nuestra promesa", promise_body: "Nada se marca como Probado hasta que otras personas que hicieron lo mismo confirmen que coincide. Sin teorías, solo experiencia verificada.", ads_title: "Anuncios", ads_body: "Llegue a una audiencia altamente comprometida y confiada. Nuestra comunidad valora la autenticidad por encima de todo.", ads_cta: "Anúnciate con nosotros" },
    products: { title: "Nuestros productos", subtitle: "Experimenta The Proven X en cualquier lugar.", web: "Comunidad Web", web_desc: "La plataforma principal para preguntar, responder y verificar.", mobile: "Aplicación móvil", mobile_desc: "Lleva la comunidad contigo. Disponible ahora.", plans: "Planes", free: "Gratis", free_desc: "Acceso completo para leer y contribuir.", paid: "Pro", paid_desc: "Funciones avanzadas y soporte prioritario.", coming_soon: "Próximamente" },
    blog: { title: "Blog", read_more: "Leer más" }
  },
  ru: {
    nav: { about: "О нас", products: "Продукты", blog: "Блог" },
    about: { title: "О The Proven X", story_title: "Наша история", story_body: "The Proven X был создан по простой причине: общие советы не работают. Мы хотим получать ответы от людей, которые действительно пережили этот опыт.", promise_title: "Наше обещание", promise_body: "Ничто не помечается как Доказанное, пока другие люди, оказавшиеся в такой же ситуации, не подтвердят это. Никаких теорий, только проверенный опыт.", ads_title: "Реклама", ads_body: "Охватите вовлеченную и доверяющую аудиторию. Наше сообщество превыше всего ценит подлинность.", ads_cta: "Разместить рекламу" },
    products: { title: "Наши продукты", subtitle: "Используйте The Proven X где угодно.", web: "Веб-сообщество", web_desc: "Основная платформа для вопросов, ответов и проверок.", mobile: "Мобильное приложение", mobile_desc: "Возьмите сообщество с собой. Доступно сейчас.", plans: "Планы", free: "Бесплатно", free_desc: "Полный доступ к чтению и участию.", paid: "Про", paid_desc: "Расширенные функции и приоритетная поддержка.", coming_soon: "Скоро" },
    blog: { title: "Блог", read_more: "Читать далее" }
  },
  uk: {
    nav: { about: "Про нас", products: "Продукти", blog: "Блог" },
    about: { title: "Про The Proven X", story_title: "Наша історія", story_body: "The Proven X був створений з простої причини: загальні поради не працюють. Ми хочемо отримувати відповіді від людей, які дійсно пережили цей досвід.", promise_title: "Наша обіцянка", promise_body: "Ніщо не позначається як Доведене, доки інші люди, які пройшли через те саме, не підтвердять це. Жодних теорій, тільки перевірений досвід.", ads_title: "Реклама", ads_body: "Охопіть залучену та довірливу аудиторію. Наша спільнота понад усе цінує справжність.", ads_cta: "Розмістити рекламу" },
    products: { title: "Наші продукти", subtitle: "Використовуйте The Proven X будь-де.", web: "Веб-спільнота", web_desc: "Основна платформа для запитань, відповідей та перевірок.", mobile: "Мобільний додаток", mobile_desc: "Візьміть спільноту з собою. Доступно зараз.", plans: "Плани", free: "Безкоштовно", free_desc: "Повний доступ до читання та участі.", paid: "Про", paid_desc: "Розширені функції та пріоритетна підтримка.", coming_soon: "Незабаром" },
    blog: { title: "Блог", read_more: "Читати далі" }
  },
  fa: {
    nav: { about: "درباره ما", products: "محصولات", blog: "وبلاگ" },
    about: { title: "درباره The Proven X", story_title: "داستان ما", story_body: "The Proven X به یک دلیل ساده ساخته شد: توصیه‌های عمومی کارساز نیستند. ما پاسخ‌هایی از افرادی می‌خواهیم که واقعاً آن را تجربه کرده‌اند.", promise_title: "تعهد ما", promise_body: "هیچ چیز تایید شده علامت‌گذاری نمی‌شود تا زمانی که دیگرانی که همان کار را انجام داده‌اند آن را تایید کنند. بدون نظریه، فقط تجربه تایید شده.", ads_title: "تبلیغات", ads_body: "به مخاطبانی متعهد و معتمد دسترسی پیدا کنید. جامعه ما اصالت را بیش از هر چیز ارزش می‌نهد.", ads_cta: "با ما تبلیغ کنید" },
    products: { title: "محصولات ما", subtitle: "تجربه The Proven X در هر مکان.", web: "جامعه وب", web_desc: "پلتفرم اصلی برای پرسش، پاسخ و تایید.", mobile: "اپلیکیشن موبایل", mobile_desc: "جامعه را همراه خود داشته باشید. هم‌اکنون در دسترس است.", plans: "برنامه‌ها", free: "رایگان", free_desc: "دسترسی کامل برای خواندن و مشارکت.", paid: "حرفه‌ای", paid_desc: "ویژگی‌های پیشرفته و پشتیبانی ویژه.", coming_soon: "به زودی" },
    blog: { title: "وبلاگ", read_more: "بیشتر بخوانید" }
  },
  ur: {
    nav: { about: "ہمارے بارے میں", products: "مصنوعات", blog: "بلاگ" },
    about: { title: "The Proven X کے بارے میں", story_title: "ہماری کہانی", story_body: "The Proven X کو ایک سادہ سی وجہ سے بنایا گیا تھا: عام مشورے کام نہیں کرتے۔ ہم ان لوگوں سے جوابات چاہتے ہیں جنہوں نے واقعی اس کا تجربہ کیا ہے۔", promise_title: "ہمارا وعدہ", promise_body: "کوئی بھی چیز اس وقت تک ثابت شدہ قرار نہیں دی جاتی جب تک کہ دوسرے لوگ جنہوں نے وہی کیا ہے اس کی تصدیق نہ کریں۔ کوئی نظریہ نہیں، صرف تصدیق شدہ تجربہ۔", ads_title: "اشتہارات", ads_body: "ایک متحرک اور پر اعتماد سامعین تک پہنچیں۔ ہماری کمیونٹی سب سے بڑھ کر اصلیت کی قدر کرتی ہے۔", ads_cta: "ہمارے ساتھ اشتہار دیں" },
    products: { title: "ہماری مصنوعات", subtitle: "The Proven X کا تجربہ کہیں بھی کریں۔", web: "ویب کمیونٹی", web_desc: "پوچھنے، جواب دینے اور تصدیق کرنے کا بنیادی پلیٹ فارم۔", mobile: "موبائل ایپ", mobile_desc: "کمیونٹی کو اپنے ساتھ لے جائیں۔ اب دستیاب ہے۔", plans: "منصوبے", free: "مفت", free_desc: "پڑھنے اور حصہ لینے کے لیے مکمل رسائی۔", paid: "پرو", paid_desc: "اعلیٰ خصوصیات اور ترجیحی تعاون۔", coming_soon: "جلد آ رہا ہے" },
    blog: { title: "بلاگ", read_more: "مزید پڑھیں" }
  },
  bn: {
    nav: { about: "সম্পর্কে", products: "পণ্য", blog: "ব্লগ" },
    about: { title: "The Proven X সম্পর্কে", story_title: "আমাদের গল্প", story_body: "The Proven X একটি সাধারণ কারণে তৈরি করা হয়েছিল: সাধারণ পরামর্শ কাজ করে কাশী। আমরা এমন লোকদের কাছ থেকে উত্তর চাই যারা সত্যিই অভিজ্ঞতা অর্জন করেছেন।", promise_title: "আমাদের প্রতিশ্রুতি", promise_body: "অন্যান্য মানুষ যারা একই কাজ করেছে তারা এটি নিশ্চিত না করা পর্যন্ত কোন কিছু প্রমাণিত হিসেবে চিহ্নিত করা হয় না। কোন তত্ত্ব নয়, শুধু যাচাইকৃত অভিজ্ঞতা।", ads_title: "বিজ্ঞাপন", ads_body: "একটি অত্যন্ত জড়িত, বিশ্বস্ত শ্রোতাদের কাছে পৌঁছান। আমাদের সম্প্রদায় সব কিছুর উপরে সত্যতাকে মূল্য দেয়।", ads_cta: "আমাদের সাথে বিজ্ঞাপন দিন" },
    products: { title: "আমাদের পণ্য", subtitle: "যে কোনো জায়গায় The Proven X অভিজ্ঞতা নিন।", web: "ওয়েব সম্প্রদায়", web_desc: "জিজ্ঞাসা, উত্তর এবং যাচাই করার জন্য মূল প্ল্যাটফর্ম।", mobile: "মোবাইল অ্যাপ", mobile_desc: "সম্প্রদায়কে আপনার সাথে নিয়ে যান। এখন উপলব্ধ।", plans: "পরিকল্পনা", free: "বিনামূল্যে", free_desc: "পড়া এবং অবদান রাখার জন্য সম্পূর্ণ অ্যাক্সেস।", paid: "প্রো", paid_desc: "উন্নত বৈশিষ্ট্য এবং অগ্রাধিকার সমর্থন।", coming_soon: "শীঘ্রই আসছে" },
    blog: { title: "ব্লগ", read_more: "আরও পড়ুন" }
  },
  tr: {
    nav: { about: "Hakkımızda", products: "Ürünler", blog: "Blog" },
    about: { title: "The Proven X Hakkında", story_title: "Hikayemiz", story_body: "The Proven X basit bir nedenden dolayı kuruldu: genel tavsiyeler işe yaramıyor. Biz bu deneyimi gerçekten yaşamış insanlardan cevaplar istiyoruz.", promise_title: "Sözümüz", promise_body: "Aynı şeyi yapan diğer insanlar onaylayana kadar hiçbir şey Kanıtlanmış olarak işaretlenmez. Teori yok, sadece doğrulanmış deneyim.", ads_title: "Reklam", ads_body: "Son derece ilgili, güvenen bir kitleye ulaşın. Topluluğumuz her şeyden önce özgünlüğe değer verir.", ads_cta: "Bizimle reklam verin" },
    products: { title: "Ürünlerimiz", subtitle: "The Proven X'i her yerde deneyimleyin.", web: "Web Topluluğu", web_desc: "Soru sormak, cevaplamak ve doğrulamak için temel platform.", mobile: "Mobil Uygulama", mobile_desc: "Topluluğu yanınızda taşıyın. Şimdi mevcut.", plans: "Planlar", free: "Ücretsiz", free_desc: "Okumak ve katkıda bulunmak için tam erişim.", paid: "Pro", paid_desc: "Gelişmiş özellikler ve öncelikli destek.", coming_soon: "Yakında" },
    blog: { title: "Blog", read_more: "Devamını Oku" }
  }
};

for (const lang of Object.keys(original)) {
  Object.assign(original[lang].translation.nav, additions[lang].nav);
  original[lang].translation.about = additions[lang].about;
  original[lang].translation.products = additions[lang].products;
  original[lang].translation.blog = additions[lang].blog;
}

const fileContent = `import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

const resources = ${JSON.stringify(original, null, 2)};

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    resources,
    fallbackLng: 'en',
    supportedLngs: ['en', 'ar', 'tl', 'hi', 'zh', 'fr', 'es', 'ru', 'uk', 'fa', 'ur', 'bn', 'tr'],
    interpolation: {
      escapeValue: false, 
    },
  });

export const isRTL = (lng: string) => ['ar', 'fa', 'ur'].includes(lng);

export default i18n;
`;

fs.writeFileSync('src/lib/i18n.ts', fileContent);
