export type PackageLimits = {
  databaseSize: string;
  monthlySessions: string;
  peakConcurrentUsers: string;
};

export type PackageTier = {
  id: string;
  name: string;
  developmentPrice: string;
  monthlyFees: string;
  limits: PackageLimits;
};

export type PackageOffer = {
  id: string;
  name: string;
  description: string;
  tiers: PackageTier[];
};

export const packagesContent = {
  title: "Our Packages",
  subtitle:
    "Launch, Growth, and Scale tiers for the websites and stores we build — limits you can plan around.",
  header: {
    brand: "TheProvenX",
    nav: [
      { href: "#our-packages", label: "Our Packages" },
      { href: "#informative-website", label: "Informative Website" },
      { href: "#e-store", label: "E-store" },
      { href: "#usage-policy", label: "Usage policy" },
    ],
  },
  tableHeaders: {
    tier: "Tier",
    databaseSize: "Database size",
    monthlySessions: "Monthly sessions",
    peakConcurrentUsers: "Peak concurrent users",
    developmentPrice: "Development price",
    monthlyFees: "Monthly fees",
  },
  packages: [
    {
      id: "informative-website",
      name: "Informative Website",
      description:
        "A clear, SEO-friendly corporate or informative site built to explain what you do and get found by the right audience.",
      tiers: [
        {
          id: "launch",
          name: "Launch",
          developmentPrice: "2,000 SAR",
          monthlyFees: "1,500 SAR",
          limits: {
            databaseSize: "1 GB",
            monthlySessions: "25,000",
            peakConcurrentUsers: "50",
          },
        },
        {
          id: "growth",
          name: "Growth",
          developmentPrice: "2,000 SAR",
          monthlyFees: "2,000 SAR",
          limits: {
            databaseSize: "5 GB",
            monthlySessions: "100,000",
            peakConcurrentUsers: "200",
          },
        },
        {
          id: "scale",
          name: "Scale",
          developmentPrice: "2,000 SAR",
          monthlyFees: "2,500 SAR",
          limits: {
            databaseSize: "20 GB",
            monthlySessions: "500,000",
            peakConcurrentUsers: "1,000",
          },
        },
      ],
    },
    {
      id: "e-store",
      name: "E-store",
      description:
        "An SEO-friendly e-commerce store designed for discovery, browsing, and checkout — without unnecessary complexity.",
      tiers: [
        {
          id: "launch",
          name: "Launch",
          developmentPrice: "3,000 SAR",
          monthlyFees: "1,800 SAR",
          limits: {
            databaseSize: "2 GB",
            monthlySessions: "40,000",
            peakConcurrentUsers: "75",
          },
        },
        {
          id: "growth",
          name: "Growth",
          developmentPrice: "3,000 SAR",
          monthlyFees: "2,300 SAR",
          limits: {
            databaseSize: "10 GB",
            monthlySessions: "150,000",
            peakConcurrentUsers: "300",
          },
        },
        {
          id: "scale",
          name: "Scale",
          developmentPrice: "3,000 SAR",
          monthlyFees: "2,800 SAR",
          limits: {
            databaseSize: "40 GB",
            monthlySessions: "750,000",
            peakConcurrentUsers: "1,500",
          },
        },
      ],
    },
  ] satisfies PackageOffer[],
  usagePolicy: {
    id: "usage-policy",
    title: "Usage and Upgrade Policy",
    paragraphs: [
      "Usage should be measured over each monthly billing period.",
      "Customers may be notified when their usage reaches approximately 80% of a package limit. Reaching or exceeding a package limit may result in an infrastructure review, an overage charge, or a recommendation to move to the next package.",
      "A temporary traffic increase does not necessarily require a permanent upgrade. However, customers who consistently exceed one or more limits may need to move to a higher package to maintain stable performance.",
      "Traffic generated by malicious bots, denial-of-service attacks, or other clearly abusive activity may be treated separately where it can be identified.",
      "Package limits represent included capacity rather than guaranteed maximum technical capacity. Website performance may also depend on application complexity, page size, integrations, background processing, media usage, and the efficiency of the website’s code.",
    ],
  },
} as const;
